# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twiple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twiple
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

  target 'TwipleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwipleUITests' do
    # Pods for testing
  end

end
